#!/usr/bin/env python
from sys import stdout, argv

instructions = open(argv[1]).read()
in_len = len(instructions)
output = stdout.write
data = bytearray(30000)
data_view = memoryview(data)
dp = 0
ip = 0
tip = None
while ip < in_len and ip >= 0:
    i = instructions[ip]
    for p in range(10): print("v" if p == dp else " "),
    print ""
    for p in data[:10]: print(hex(p)[-1]),
    print "\t%s dp:%s" % (i, dp)
    if i is '>':
        dp += 1
    elif i is '<':
        dp -= 1
    elif i is '+':
        data[dp] += 1
    elif i is '-':
        data[dp] -= 1
    elif i is '.':
        output(data_view[dp])
    elif i is '[':
        if not data[dp]:
            tip = ip + 1
            l = 0
            while tip < in_len:
                if instructions[tip] is ']':
                    if l == 0:
                        break
                    else:
                        l -= 1
                elif instructions[tip] is '[':
                    l += 1
                tip += 1
            ip = tip
    elif i is ']':
        if data[dp]:
            tip = ip - 1
            l = 0
            while tip >= 0:
                if instructions[tip] is '[':
                    if l == 0:
                        break
                    else:
                        l -= 1
                elif instructions[tip] is ']':
                    l += 1
                tip -= 1
            ip = tip
    ip += 1

